name: caramelseed
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.7
  cupertino_icons: ^0.1.3
  json_annotation: ^3.0.1
  flutter_bloc: ^4.0.0
  equatable: ^1.1.1
  get_it: ^4.0.2
  dartz: ^0.9.0
  data_connection_checker: ^0.3.4
  http: ^0.12.1
  meta: ^1.1.8
  page_transition: ^1.1.5
  flutter_spinkit: '^4.1.2'
  path_provider: ^1.6.5
  flutter_data: ^0.3.11
  firebase_auth: ^0.16.0
  google_sign_in: ^4.5.1
  flutter_auth_buttons: ^0.8.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  lint: ^1.1.1
  test: ^1.09.0
  git_hooks: ^0.0.4
  build_runner: ^1.9.0
  json_serializable: ^3.3.0
  bloc_test: ^5.0.0

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Medium.ttf
          style: normal
        - asset: fonts/Roboto-MediumItalic.ttf
          style: italic
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
